services:
  redis:
    image: redis:8.0.2
    container_name: chat-app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - chat-app-network

volumes:
  redis_data:
    name: chat-app-redis-data

networks:
  chat-app-network:
    name: chat-app-network
