spring:
  config:
    import: file:env.properties
  application:
    name: chat-app
  datasource:
    url: jdbc:mysql://localhost:3306/chat-app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB

server:
  port: 9000

jwt:
  signerKey: ${JWT_SIGNER_KEY}

fe:
  url: http://localhost:63342

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    org.springframework.security: DEBUG

