spring:
  config:
    import: file:env.properties
  application:
    name: chat-app
  datasource:
    url: jdbc:mysql://localhost:3306/chat-app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9000

jwt:
  signerKey: ${JWT_SIGNER_KEY}

fe:
  url: http://127.0.0.1:5500
